repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0c0af8f5055b092cc0ffb90e20ae4a03af3a0e8a  # frozen: 0.7.11
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-toc
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/asottile/yesqa
  rev: 35cf7dc24fa922927caded7a21b2a8cb04bf8e10  # frozen: v1.3.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/PyCQA/isort
  rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: f1d4e742c91dd5179d742b0db9293c4472b765f8  # frozen: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/myint/docformatter
  rev: 67919ee01837761f2d954d7fbb08c12cdd38ec5a  # frozen: v1.4
  hooks:
  - id: docformatter
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
  hooks:
  - id: check-yaml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 6f51a66bba59954917140ec2eeeaa4d5e630e6ce  # frozen: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/PyCQA/flake8
  rev: cbeb4c9c4137cff1568659fcc48e8b85cddd0c8d  # frozen: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 5ecfb11dc5d24c184a754017ca3a38cb23278d26  # frozen: v0.920
  hooks:
  - id: mypy
    args: ["--scripts-are-modules"]
    additional_dependencies:
    - types-python-dateutil
    - pytest
